### ISSUE TITLE
IvyWallet include future planned payment

### ISSUE THREAD

**Issue by Thunder33345** [uderbashi/IvyWallet-Cashew-CSV-Converter#3]
It seems like IvyWallet omits date for future planned payments, and instead populates it with a due date

sample entry from my export:
```
Date,Title,Category,Account,Amount,Currency,Type,Transfer Amount,Transfer Currency,To Account,Receive Amount,Receive Currency,Description,Due Date,ID
,Work,General,Bank,"1234.56",USD,INCOME,,,,,,,2024-11-21T12:34:00,8621cfde-bb88-458c-b6d3-40d99beb9d8e
,Work,General,Bank,"1234.56",USD,INCOME,,,,,,,2024-12-21T12:34:00,7018c231-134b-40ae-b8b3-16c19b806c9b
,Work,General,Bank,"1234.56",USD,INCOME,,,,,,,2025-01-21T12:34:00,8959d834-50b0-4ca9-aeb2-5df20fc8c629
```

**Comment by uderbashi** [comment]
Thanks for the commit.
@Thunder33345 I just edited the error message, would you mind trying to run it with your CSV (I don't have a csv ready now to run) just to make sure it does not give any errors?

**Comment by Thunder33345** [comment]
@uderbashi Looks good to me, thanks for fixing the message, I tested it, and there are no issues here
but it seems like there's a typo in "paymnet" though, which should been "payment"
```
Warning: an entry with no date is ignored: Title "Work" Amount "1234.56". Most likely to be a future paymnet due in 2027-08-17T20:00:00.
```

**Comment by uderbashi** [comment]
> but it seems like there's a typo in "paymnet" though, which should been "payment"

Very sharp eye... Thanks for spotting it. I am fixing the typo and merging into main.
